### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by jecaJeca** [ZhouYiiFeng/TDMS-Net#1]
Hello,

Would it be possible for you to upload pretrained models ?

Thanks!

**Comment by ZhouYiiFeng** [comment]
The pretrained models are uploaded on the Baidu NetDisk.

**Comment by jecaJeca** [comment]
Thanks a lot!

**Comment by jecaJeca** [comment]
Hello again,

It seems that some modules are still missing. When I run test_TDMS_Net.py I am getting this error : 

 from networks.flownet2_pytorch.networks.resample2d_package.resample2d import Resample2d
ModuleNotFoundError: No module named 'networks.flownet2_pytorch.networks'

Also, regarding testing on my own dataset,why it is necessary to specify task (such as WCT/wave in the example)? I understand that the model is blind regarding the task? 

Thanks again for your quick response! Amazing work!

**Comment by ZhouYiiFeng** [comment]
> from networks.flownet2_pytorch.networks.resample2d_package.resample2d import Resample2d ModuleNotFoundError: No module named 'networks.flownet2_pytorch.networks'

This error reports that there's some problem in your flownet2 env, correct it by referring [flownet2](https://github.com/NVIDIA/flownet2-pytorch) and put the whole flownet2 project into network dir.

> Also, regarding testing on my own dataset, why it is necessary to specify tasks (such as WCT/wave in the example)? I understand that the model is blind regarding the task?

As shown in the code, it needs the task name to locate the path of the video sequence, TDMSNet is the blind denoise network.

**Comment by jecaJeca** [comment]
Ok, I get it! Thanks a lot,  I successfully tested it on my video. The consistency is there, really amazing! It is just that video is getting darker and darker as processing frames progress (the brightness of whole frame is reducing). Last frame is very, very dark. Do you have some idea what can cause this?

**Comment by ZhouYiiFeng** [comment]
> It is just that video is getting darker and darker as processing frames progress (the brightness of the whole frame is reducing)

As mentioned in the paper, this is exactly the problem with TDMSNet. The main reason for this problem is discussed in the paper.

**TO AVOID** this, you could try:
- Divide your video into small pieces, and process it independently.
- Adjust the weight of motion mask, meanwhile, increase the LPIPS weight when training the TDMSNet.

I hope these tips could help you to sovle your problem.

**Comment by jecaJeca** [comment]
Thanks. I couldn't find whole paper online (free access), just your presentation. It would be great if you can put it somewhere online.

I will close this issue with this comment! Thanks for being very responsive and available for discussion!
