### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by crenaudineau1** [ZhouYiiFeng/TDMS-Net#2]
Hello,

Thanks for your work. Could you release working code ?

Thanks a lot.

**Comment by ZhouYiiFeng** [comment]
Hi,

The training code is only released for research purposes. When this project has gained enough attention, I will consider releasing the full version of the code.

**Comment by crenaudineau1** [comment]
Hi,

Thanks for your responds. We are working with the University of Strasbourg on video consistency problem. To compare and improve our result, we need your training code. Which email can I contact you ?

**Comment by ZhouYiiFeng** [comment]
My Gmail:  joeyf.z.y.wen@gmail.com
