### ISSUE TITLE
pretrained wights

### ISSUE THREAD

**Issue by AMontiB** [ZhouYiiFeng/TDMS-Net#5]
Could you upload the weights on a platform that does not require downloading its client?
Regards,

**Comment by MrPalais** [comment]
same thing here. please.

**Comment by hcl14** [comment]
Here is checkpoint file:

[https://drive.google.com/file/d/1nZ3IxyaLLzHShodDHocbAKDHgZh417U9/view?usp=sharing](https://drive.google.com/file/d/1nZ3IxyaLLzHShodDHocbAKDHgZh417U9/view?usp=sharing)

Baidu client wanted to download also "results.zip" of size 14GB, I didn't do that - don't know if it's my bug or it was also present by this link. Tell me if its needed and it will try download it as well

**Comment by MrPalais** [comment]
> Here is checkpoint file:
> 
> https://drive.google.com/file/d/1nZ3IxyaLLzHShodDHocbAKDHgZh417U9/view?usp=sharing
> 
> Baidu client wanted to download also "results.zip" of size 14GB, I didn't do that - don't know if it's my bug or it was also present by this link. Tell me if its needed and it will try download it as well

Grreat ! Thanks a lot Egor !

I think the other file is just samples.

**Comment by AMontiB** [comment]
Thank you!
